name: E2E test

on:
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List failed jobs
        id: list-failed-jobs
        working-directory: packages/cli
        run: |
          result=`curl \
            -u :${{ secrets.GITHUB_TOKEN }}\
            https://api.github.com/repos/OfficeDev/TeamsFx/actions/runs/1755580895/attempts/1/jobs?per_page=100`

          cases=`echo $result | jq -r '.jobs[] | select(.name | contains("tests.ts")) | .name'`

          description="<tr> <th>Case</th> <th>Status</th> <th>Author</th> </tr>"

          emails="vsciotadt@microsoft.com"
          while IFS= read -r case;
          do
            echo $case
            if [ -z "$case" ]; then
              continue
            fi

            file="tests/e2e/$case"
            email=`cat $file | grep '@author' | grep -i -o '[A-Z0-9._%+-]\+@[A-Z0-9.-]\+\.[A-Z]\{2,4\}'`
            status=`echo $result | jq --arg case $case -r '.jobs[] | select(.name == $case ) | .conclusion'`

            if [[ ! "$emails" == *"$email"* && "$status" == "failure" ]]; then
              emails="$emails;$email"
            fi
            
            label=""
            if [ "$status" == "success" ]; then
              label="<span class=\"label success\">success</span>"
            else
              label="<span class=\"label danger\">failure</span>"
            fi
            echo $label

            author=""
            if [ -z "$email" ]; then
              author="N/A"
            else
              author="<a href=\"mailto:$email\"><span>$email</span></a>"
            fi
            echo $author

            description="$description <tr> <td>$file</td> <td>$label<td> <td>$author</td> </tr> "
          done <<< $cases

          echo "::set-output name=description::$description"

      - name: Send E-mail to the whole team
        uses: satak/webrequest-action@master
        with:
          url: https://prod-30.eastus.logic.azure.com:443/workflows/9aa865da96054bd89749c2d4ce68df8e/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uIoB06NUHSnKoZeWjNDI9t4rrhbTBKxJNiBtDoMRSQs
          method: POST
          payload: |
            {
              "to": "haolong@microsoft.com",
              "body": "<table class=\"w3-table w3-striped w3-bordered\">${{ steps.list-failed-jobs.outputs.description }}</table> <br /> The detail can be found here: https://github.com/OfficeDev/TeamsFx/actions/runs/${{ github.run_id }}",
              "subject": "[Failure] TeamsFx CLI E2E Test ${{ github.run-id }}",
              "apiKey": "${{ secrets.MAIL_API_KEY }}"
            }
